# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-13 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='姓名')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
            ],
        ),
    ]
